// Exportar el cliente API
export { default as apiClient } from './client';

// Exportar tipos
export type {
  StrapiResponse,
  StrapiEntity,
  StrapiImage,
  BiomeName,
  RarityName,
  Monster,
  World,
  Place,
  Region,
  Item,
  Companion,
  InventoryEntry,
  BuyResponse,
  ShopStock,
  ShopStockLine,
  DiscoveryTask,
  DiscoveryStrategy,
  DiscoveryEventType,
  DiscoveryEventRequest,
  DiscoveryResponse,
  EventStatus,
  EventStepView,
  EventView,
  EventRewardResult,
  EventStepResponse,
  DuelStatus,
  DuelSide,
  BattleAction,
  DuelSummary,
  DuelsLobby,
  BattleItem,
  BattleCompanion,
  DuelDetail,
  BattleFighter,
  BattleState,
  BattleLogEntry,
  BattleResult,
  GameStatus,
  GameClaimResponse,
  TrainingInfo,
  TrainerInfo,
  TrainStat,
  TrainStatRow,
  DemandedTotem,
  HouseVisibility,
  HouseDesignInfo,
  NeighborhoodParcel,
  NeighborhoodParcels,
  HouseDesign,
  HousePlacement,
  House,
  HouseResponse,
  HouseBuyResponse,
  MonstersResponse,
  WorldsResponse,
  PlacesResponse,
  RegionsResponse,
  ItemsResponse,
  CompanionsResponse,
  InventoryEntriesResponse,
  MonsterResponse,
  WorldResponse,
  PlaceResponse,
  RegionResponse,
  ItemResponse,
  QueryParams,
  ApiError,
  AuthUser,
  LoginRequest,
  RegisterRequest,
  AuthResponse,
  AuthError
} from './types';

// Exportar servicios
export {
  monstersService,
  worldsService,
  placesService,
  regionsService,
  itemsService,
  companionsService,
  inventoryService,
  shopService,
  discoveryService,
  eventsService,
  battleService,
  gamesService,
  trainingService,
  housesService,
  dataService,
  authService
} from './services';

// Exportar hooks
export {
  useHomeData,
  useExploreData,
  useMonsters,
  useWorlds,
  usePlaces,
  usePlacesByWorld,
  useWorld,
  useRegion,
  usePlace,
  useMonster,
  useItems,
  useItemsByType,
  useItemsByRarity,
  useActiveCompanion,
  useInventory,
  useDiscoveredMonsters,
  useActiveEvents,
  useLogin,
  useRegister,
  useGetMe
} from './hooks';
